<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Username atau Password SalahClose</name>
   <tag></tag>
   <elementGuidId>7d1502b3-6e5c-454c-9d64-577b962f177d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='errorMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#errorMessage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5e9e3d07-3737-4884-8052-9ee7ba47e9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative w-1/2 mt-10</value>
      <webElementGuid>31401cae-aa60-42b6-a671-1e7b7204da7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>24b4ee39-0b6a-4469-98f3-b523e497eb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errorMessage</value>
      <webElementGuid>9283ade2-7b25-442f-8ff3-fb166e910d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username atau Password SalahClose</value>
      <webElementGuid>34dfcbf4-996a-48b1-97cd-f1fd68601b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errorMessage&quot;)</value>
      <webElementGuid>21458fd5-797e-4d58-9c61-98e93b13a0bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='errorMessage']</value>
      <webElementGuid>963a299f-b990-44d5-8377-39ac176c34b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div</value>
      <webElementGuid>a817e654-6836-426c-8c9e-aa93067fa128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login to your account'])[1]/following::div[2]</value>
      <webElementGuid>989abf63-7bde-4830-bbb4-0410680881b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username address'])[1]/preceding::div[1]</value>
      <webElementGuid>510b14a9-05b6-4bda-a440-12aa6a9c68c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>6087a555-39f2-40f0-b524-4129cbf62fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'errorMessage' and (text() = 'Username atau Password SalahClose' or . = 'Username atau Password SalahClose')]</value>
      <webElementGuid>be13aa46-54d8-472b-b298-d554a83cc148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
